/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <zp50_core>
#include <zp50_grenade_frost>

#define PLUGIN "[ZP 5.0] First Zombie"
#define VERSION "1.0"
#define AUTHOR "VINAGHOST"


public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
}

public zp_fw_grenade_frost_pre(id) {
	if( zp_core_is_first_zombie(id) )
	{
		return PLUGIN_CONTINUE;
	}
	return PLUGIN_HANDLED
}
