/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <fakemeta>
#include <zp50_items>
#include <zp50_gamemodes>
#include <zp50_colorchat>

#define PLUGIN "[ZP] Item: Double AP"
#define VERSION "1.0"
#define AUTHOR "VINAGHOST"


#define ITEM_NAME "x2 AP"
#define ITEM_COST 5

#define flag_get(%1,%2) (%1 & (1 << (%2 & 31)))
#define flag_get_boolean(%1,%2) (flag_get(%1,%2) ? true : false)
#define flag_set(%1,%2) %1 |= (1 << (%2 & 31))
#define flag_unset(%1,%2) %1 &= ~(1 << (%2 & 31))

new g_ItemID

new g_Double
public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	g_ItemID = zp_ap_items_register(ITEM_NAME, ITEM_COST)
}
public plugin_natives() {
	register_native("zp_get_doubleAP", "is_haveItem")
}
public is_haveItem() {
	new id = get_param(1);
	
	return flag_get(g_Double, id);
}
public zp_fw_ap_items_select_pre(id, itemid, ignorecost)
{
	if (itemid != g_ItemID)
		return ZP_ITEM_AVAILABLE;
	
	if (  flag_get(g_Double, id)  )
		return ZP_ITEM_NOT_AVAILABLE;
	
	return ZP_ITEM_AVAILABLE;
}

public zp_fw_ap_items_select_post(id, itemid, ignorecost)
{
	// This is not our item
	if (itemid != g_ItemID)
		return;
	
	flag_set(g_Double, id);
	
	zp_colored_print(id, "Da kich hoat %s", ITEM_NAME);
}

public client_disconnect(id) {
	if(flag_get(g_Double, id) )
		flag_unset(g_Double, id)
}
