/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <fakemeta>
#include <zp50_items>
#include <zp50_gamemodes>


#define PLUGIN "[ZP] Item: Invis"
#define VERSION "1.0"
#define AUTHOR "VINAGHOST"


#define ITEM_NAME "Tang hinh trong 30s"
#define ITEM_COST 17000

#define flag_get(%1,%2) (%1 & (1 << (%2 & 31)))
#define flag_get_boolean(%1,%2) (flag_get(%1,%2) ? true : false)
#define flag_set(%1,%2) %1 |= (1 << (%2 & 31))
#define flag_unset(%1,%2) %1 &= ~(1 << (%2 & 31))

#define TASKID 80
new g_ItemID

new g_Invis;
public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	g_ItemID = zp_money_items_register(ITEM_NAME, ITEM_COST)
}
public zp_fw_ap_items_select_pre(id, itemid, ignorecost)
{
	if (itemid != g_ItemID)
		return ZP_ITEM_AVAILABLE;
	
	if (  flag_get(g_Invis, id)  )
		return ZP_ITEM_NOT_AVAILABLE;
	
	return ZP_ITEM_AVAILABLE;
}

public zp_fw_ap_items_select_post(id, itemid, ignorecost)
{
	// This is not our item
	if (itemid != g_ItemID)
		return;
	
	Invisible(id)
	
	set_task(30.0, "Vis", id + TASKID);
}

public zp_fw_core_spawn_post(id) {
	
	if(flag_get(g_Invis, id) )
		flag_unset(g_Invis, id)
}
public zp_fw_core_cure_post(id) {
	if(flag_get(g_Invis, id) ) {
		remove_task(id + TASKID);
	}
}
public zp_fw_core_infect_post(id) {
	if(flag_get(g_Invis, id) ) {
		remove_task(id + TASKID);
	}
}

public Vis(id) {
	id -= TASKID
	
	Visible(id)
}

public Invisible(id) {
	fm_set_entity_visibility(id, 0)
	flag_set(g_Invis, id);
	
}
public Visible(id) {
	fm_set_entity_visibility(id)
	flag_unset(g_Invis, id)
}

stock fm_set_entity_visibility(index, visible = 1) { 
    set_pev(index, pev_effects, visible == 1 ? pev(index, pev_effects) & ~EF_NODRAW : pev(index, pev_effects) | EF_NODRAW); 

    return 1; 
} 
